  
steps:
  ###########################################
  ###               DEPLOY                ###
  ###########################################
  - id: 'pull-cache-image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker pull gcr.io/oa-devel/freezer:cache || exit 0
  - id: 'build-image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/oa-devel/freezer:${COMMIT_SHA}',
             '--cache-from', 'gcr.io/oa-devel/freezer:cache', '.']

  - id: 'tag-cache-image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/oa-devel/freezer:${COMMIT_SHA}', 'gcr.io/oa-devel/freezer:cache']
  
  - id: 'docker-push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/oa-devel/freezer']

  - id: 'deploy-cloud-run'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'freezer', '--platform', 'managed', '--image', 'gcr.io/oa-devel/freezer:${COMMIT_SHA}',
           '--allow-unauthenticated', '--project', 'freezer-308311', '--region', 'europe-west1']
id: 'deploy'